name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI PR Review
        uses: pritom007/ai-pr-review@v1
        with:
          api-key: ${{ secrets.INPUT_API_KEY }}
          model-name: 'gpt-4' # you can use any other LLM model
          base-url: 'https://api.openai.com' # you can use deepseek, gorq, or any other LLM provider
          temperature: '0.7'
          max-tokens: '1000' # Optional
          language: 'English'